<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Yae</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFramework>net9.0-windows</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <PublishAot>true</PublishAot>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <InvariantGlobalization>true</InvariantGlobalization>
        <OptimizationPreference>Speed</OptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <DirectPInvoke Include="NTDLL" />
        <DirectPInvoke Include="USER32" />
        <DirectPInvoke Include="KERNEL32" />
        <DirectPInvoke Include="libMinHook.x64" />
        <NativeLibrary Include="lib\libMinHook.x64.lib" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Diagnostics" />
        <Using Include="System.Diagnostics.CodeAnalysis" />
    </ItemGroup>

    <PropertyGroup>
        <PackageId>Yae.Lib</PackageId>
        <Version>5.5.0</Version>
        <Authors>HoloHat</Authors>
        <DevelopmentDependency>true</DevelopmentDependency>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/HolographicHat/Yae</RepositoryUrl>
        <Description>Yae Lib</Description>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(PublishDir)\$(TargetName)$(NativeBinaryExt)" Pack="true" PackagePath="runtimes\win-x64\native" Visible="false" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference OutputItemType="Analyzer" Include="..\YaeAchievement.SourceGeneration\YaeAchievement.SourceGeneration.csproj">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </ProjectReference>
    </ItemGroup>

    <Target Name="GenerateNuGetPackage" AfterTargets="CopyNativeBinary">
        <Exec Command="dotnet pack --no-build --nologo" UseUtf8Encoding="Always" EchoOff="true" />
    </Target>

</Project>
