//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaeAchievement.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaeAchievement.res.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all achievement.
        /// </summary>
        internal static string AllAchievement {
            get {
                return ResourceManager.GetString("AllAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close another instance..
        /// </summary>
        internal static string AnotherInstance {
            get {
                return ResourceManager.GetString("AnotherInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YaeAchievement ({0}).
        /// </summary>
        internal static string AppBanner {
            get {
                return ResourceManager.GetString("AppBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please launch GenshinImpact to continue..
        /// </summary>
        internal static string ConfigNeedStartGenshin {
            get {
                return ResourceManager.GetString("ConfigNeedStartGenshin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download: {0}.
        /// </summary>
        internal static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error ({0}: {1}).
        /// </summary>
        internal static string ExceptionNetwork {
            get {
                return ResourceManager.GetString("ExceptionNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to:.
        /// </summary>
        internal static string ExportChoose {
            get {
                return ResourceManager.GetString("ExportChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocogoat (https://cocogoat.work/achievement).
        /// </summary>
        internal static string ExportTargetCocogoat {
            get {
                return ResourceManager.GetString("ExportTargetCocogoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv file.
        /// </summary>
        internal static string ExportTargetCsv {
            get {
                return ResourceManager.GetString("ExportTargetCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap.HuTao.
        /// </summary>
        internal static string ExportTargetHuTao {
            get {
                return ResourceManager.GetString("ExportTargetHuTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paimon.moe.
        /// </summary>
        internal static string ExportTargetPaimon {
            get {
                return ResourceManager.GetString("ExportTargetPaimon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seelie.me.
        /// </summary>
        internal static string ExportTargetSeelie {
            get {
                return ResourceManager.GetString("ExportTargetSeelie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teyvat Guide.
        /// </summary>
        internal static string ExportTargetTeyvatGuide {
            get {
                return ResourceManager.GetString("ExportTargetTeyvatGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAF JSON File.
        /// </summary>
        internal static string ExportTargetUIAFJson {
            get {
                return ResourceManager.GetString("ExportTargetUIAFJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportTargetWxApp1 {
            get {
                return ResourceManager.GetString("ExportTargetWxApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xunkong.
        /// </summary>
        internal static string ExportTargetXunkong {
            get {
                return ResourceManager.GetString("ExportTargetXunkong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail, please contact developer to get help information (CG_{0}).
        /// </summary>
        internal static string ExportToCocogoatFail {
            get {
                return ResourceManager.GetString("ExportToCocogoatFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to cocogoat..
        /// </summary>
        internal static string ExportToCocogoatSuccess {
            get {
                return ResourceManager.GetString("ExportToCocogoatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to {0}.
        /// </summary>
        internal static string ExportToFileSuccess {
            get {
                return ResourceManager.GetString("ExportToFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update Snap Hutao and retry..
        /// </summary>
        internal static string ExportToSnapGenshinNeedUpdate {
            get {
                return ResourceManager.GetString("ExportToSnapGenshinNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to Snap Hutao..
        /// </summary>
        internal static string ExportToSnapGenshinSuccess {
            get {
                return ResourceManager.GetString("ExportToSnapGenshinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please launch/update Teyvat Guide and retry..
        /// </summary>
        internal static string ExportToTauriFail {
            get {
                return ResourceManager.GetString("ExportToTauriFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to Teyvat Guide..
        /// </summary>
        internal static string ExportToTauriSuccess {
            get {
                return ResourceManager.GetString("ExportToTauriSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ExportToWxApp1Success {
            get {
                return ResourceManager.GetString("ExportToWxApp1Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update xunkong and retry..
        /// </summary>
        internal static string ExportToXunkongNeedUpdate {
            get {
                return ResourceManager.GetString("ExportToXunkongNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported to xunkong..
        /// </summary>
        internal static string ExportToXunkongSuccess {
            get {
                return ResourceManager.GetString("ExportToXunkongSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game process start ({0}).
        /// </summary>
        internal static string GameLoading {
            get {
                return ResourceManager.GetString("GameLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game exited..
        /// </summary>
        internal static string GameProcessExit {
            get {
                return ResourceManager.GetString("GameProcessExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update genshin and retry..
        /// </summary>
        internal static string GenshinHashError {
            get {
                return ResourceManager.GetString("GenshinHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close game before run this application. ({0}).
        /// </summary>
        internal static string GenshinIsRunning {
            get {
                return ResourceManager.GetString("GenshinIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed. Please retry. ({0} {1} {2}).
        /// </summary>
        internal static string LoadLibraryFail {
            get {
                return ResourceManager.GetString("LoadLibraryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error:.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No write permission on {0}..
        /// </summary>
        internal static string NoWritePermission {
            get {
                return ResourceManager.GetString("NoWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit..
        /// </summary>
        internal static string PressKeyToExit {
            get {
                return ResourceManager.GetString("PressKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the keyboard arrow keys to move the cursor and the Enter key to select.
        /// </summary>
        internal static string SelectionPromptCompatAnsiTip {
            get {
                return ResourceManager.GetString("SelectionPromptCompatAnsiTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option:.
        /// </summary>
        internal static string SelectionPromptCompatChooseOne {
            get {
                return ResourceManager.GetString("SelectionPromptCompatChooseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 0 and {0}.
        /// </summary>
        internal static string SelectionPromptCompatInvalidChoice {
            get {
                return ResourceManager.GetString("SelectionPromptCompatInvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a number and press Enter to select.
        /// </summary>
        internal static string SelectionPromptCompatNonAnsiTip {
            get {
                return ResourceManager.GetString("SelectionPromptCompatNonAnsiTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward not taken.
        /// </summary>
        internal static string StatusFinished {
            get {
                return ResourceManager.GetString("StatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string StatusInvalid {
            get {
                return ResourceManager.GetString("StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string StatusRewardTaken {
            get {
                return ResourceManager.GetString("StatusRewardTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished.
        /// </summary>
        internal static string StatusUnfinished {
            get {
                return ResourceManager.GetString("StatusUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the data. Please try again..
        /// </summary>
        internal static string StreamReadDataFail {
            get {
                return ResourceManager.GetString("StreamReadDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking update....
        /// </summary>
        internal static string UpdateChecking {
            get {
                return ResourceManager.GetString("UpdateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: 
        ///{0}.
        /// </summary>
        internal static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update package....
        /// </summary>
        internal static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file &apos;{0}&apos; because it is being used by another process. Please restart your computer and try again..
        /// </summary>
        internal static string UpdateFileShareViolation {
            get {
                return ResourceManager.GetString("UpdateFileShareViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has update: {0} =&gt; {1}.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload error to appcenter....
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use previous fetched data?.
        /// </summary>
        internal static string UsePreviousData {
            get {
                return ResourceManager.GetString("UsePreviousData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Visual C++ Redistributable....
        /// </summary>
        internal static string VcRuntimeDownload {
            get {
                return ResourceManager.GetString("VcRuntimeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Visual C++ Redistributable....
        /// </summary>
        internal static string VcRuntimeInstalling {
            get {
                return ResourceManager.GetString("VcRuntimeInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update game and retry..
        /// </summary>
        internal static string WaitMetadataUpdate {
            get {
                return ResourceManager.GetString("WaitMetadataUpdate", resourceCulture);
            }
        }
    }
}
